import type {
  ReportDetail,
  RoutineDetail,
  VerificationStandard,
} from "./types";

export const REPORTS: ReportDetail[] = [
  {
    id: 1,
    title: "1号机组·废气",
    type: "gas",
    date: "2026-01-05",
    agency: "华能检测",
    status: "pass",
    nextDate: "2026-04-05",
    dueLabel: "4天后到期",
    dueLevel: "very-soon",
    urgent: true,
    reportNo: "HN-Q1-2026-G01",
    unit: "1号机组",
    outlet: "废气排放口01",
    samplingPeriod: "2026-01-03 ~ 2026-01-04",
    formItems: [
      { label: "氮氧化物 NOx", reportValue: "HJ 692-2014", requiredValue: "HJ 692-2014", pass: true },
      { label: "二氧化硫 SO₂", reportValue: "HJ 57-2017", requiredValue: "HJ 57-2017", pass: true },
      { label: "颗粒物", reportValue: "GB/T 16157-1996", requiredValue: "GB/T 16157-1996", pass: true },
      { label: "烟气流速", reportValue: "GB/T 16157-1996", requiredValue: "GB/T 16157-1996", pass: true },
    ],
    instrumentItems: [
      { name: "烟气分析仪", model: "Testo 350", calibrationDate: "2025-11-12", certValidUntil: "2026-11-11", pass: true },
      { name: "颗粒物采样器", model: "崂应 3012H", calibrationDate: "2025-12-01", certValidUntil: "2026-11-30", pass: true },
      { name: "皮托管", model: "S 型", calibrationDate: "2025-10-15", certValidUntil: "2026-10-14", pass: true },
    ],
    samplingItems: [
      {
        indicator: "氮氧化物 NOx",
        sampleCount: 6,
        minRequired: 5,
        reportMean: "48.3 mg/m³",
        cemsMean: "46.7 mg/m³",
        deviation: "+3.4%",
        maxDeviation: "±15%",
        pass: true,
      },
      {
        indicator: "二氧化硫 SO₂",
        sampleCount: 6,
        minRequired: 5,
        reportMean: "12.5 mg/m³",
        cemsMean: "13.1 mg/m³",
        deviation: "-4.6%",
        maxDeviation: "±15%",
        pass: true,
      },
      {
        indicator: "颗粒物",
        sampleCount: 6,
        minRequired: 5,
        reportMean: "4.8 mg/m³",
        cemsMean: "4.6 mg/m³",
        deviation: "+4.3%",
        maxDeviation: "±20%",
        pass: true,
      },
    ],
    attachments: [
      { id: 1, name: "1号机组废气检测报告.pdf", size: "3.2 MB", type: "pdf" },
      { id: 2, name: "采样现场照片.zip", size: "8.7 MB", type: "image" },
      { id: 3, name: "仪器校准证书.pdf", size: "1.1 MB", type: "pdf" },
    ],
    reviewLogs: [
      { id: 1, actor: "系统", action: "自动核验通过", time: "2026-01-05 16:42" },
    ],
  },
  {
    id: 2,
    title: "2号机组·废水",
    type: "water",
    date: "2026-01-08",
    agency: "华能检测",
    status: "pass",
    nextDate: "2026-04-08",
    dueLabel: "8天后到期",
    dueLevel: "soon",
    urgent: true,
    reportNo: "HN-Q1-2026-W02",
    unit: "2号机组",
    outlet: "废水排放口01",
    samplingPeriod: "2026-01-06 ~ 2026-01-07",
    formItems: [
      { label: "化学需氧量 COD", reportValue: "HJ 828-2017", requiredValue: "HJ 828-2017", pass: true },
      { label: "氨氮", reportValue: "HJ 535-2009", requiredValue: "HJ 535-2009", pass: true },
      { label: "总磷", reportValue: "GB 11893-89", requiredValue: "GB 11893-89", pass: true },
      { label: "pH", reportValue: "HJ 1147-2020", requiredValue: "HJ 1147-2020", pass: true },
    ],
    instrumentItems: [
      { name: "紫外分光光度计", model: "T6 新世纪", calibrationDate: "2025-11-20", certValidUntil: "2026-11-19", pass: true },
      { name: "便携式 pH 计", model: "HACH HQ40d", calibrationDate: "2025-12-05", certValidUntil: "2026-12-04", pass: true },
    ],
    samplingItems: [
      {
        indicator: "COD",
        sampleCount: 5,
        minRequired: 4,
        reportMean: "32 mg/L",
        cemsMean: "30 mg/L",
        deviation: "+6.7%",
        maxDeviation: "±20%",
        pass: true,
      },
      {
        indicator: "氨氮",
        sampleCount: 5,
        minRequired: 4,
        reportMean: "1.8 mg/L",
        cemsMean: "1.6 mg/L",
        deviation: "+12.5%",
        maxDeviation: "±20%",
        pass: true,
      },
    ],
    attachments: [
      { id: 1, name: "2号机组废水检测报告.pdf", size: "2.8 MB", type: "pdf" },
      { id: 2, name: "采样现场照片.zip", size: "6.5 MB", type: "image" },
    ],
    reviewLogs: [
      { id: 1, actor: "系统", action: "自动核验通过", time: "2026-01-08 17:15" },
    ],
  },
  {
    id: 3,
    title: "1号机组·噪声",
    type: "noise",
    date: "2026-01-10",
    agency: "华能检测",
    status: "pending",
    nextDate: "2026-04-10",
    dueLabel: "25天后",
    dueLevel: "normal",
    reportNo: "HN-Q1-2026-N01",
    unit: "1号机组",
    outlet: "厂界四角",
    samplingPeriod: "2026-01-09",
    formItems: [
      { label: "测量方法", reportValue: "GB 12348-2008", requiredValue: "GB 12348-2008", pass: true },
      { label: "声级计", reportValue: "II 级", requiredValue: "II 级及以上", pass: true },
    ],
    instrumentItems: [
      { name: "声级计", model: "AWA5688", calibrationDate: "2025-10-25", certValidUntil: "2026-10-24", pass: true },
    ],
    samplingItems: [],
    noiseItems: [
      { pointName: "厂界东", duration: "20 min", minDuration: "≥10 min", value: "53.2 dB(A)", limit: "60 dB(A)", pass: true },
      { pointName: "厂界南", duration: "20 min", minDuration: "≥10 min", value: "54.1 dB(A)", limit: "60 dB(A)", pass: true },
      { pointName: "厂界西", duration: "20 min", minDuration: "≥10 min", value: "52.8 dB(A)", limit: "60 dB(A)", pass: true },
      { pointName: "厂界北", duration: "20 min", minDuration: "≥10 min", value: "55.4 dB(A)", limit: "60 dB(A)", pass: true },
    ],
    attachments: [
      { id: 1, name: "1号机组噪声检测报告.pdf", size: "1.6 MB", type: "pdf" },
    ],
    reviewLogs: [
      { id: 1, actor: "系统", action: "等待数据填报", time: "2026-01-10 09:00" },
    ],
  },
  {
    id: 4,
    title: "2号机组·废气",
    type: "gas",
    date: "2026-01-12",
    agency: "华能检测",
    status: "fail",
    nextDate: "2026-04-12",
    dueLabel: "27天后",
    dueLevel: "normal",
    danger: true,
    failCount: 2,
    reportNo: "HN-Q1-2026-G02",
    unit: "2号机组",
    outlet: "废气排放口02",
    samplingPeriod: "2026-01-10 ~ 2026-01-11",
    formItems: [
      { label: "氮氧化物 NOx", reportValue: "HJ 692-2014", requiredValue: "HJ 692-2014", pass: true },
      { label: "二氧化硫 SO₂", reportValue: "HJ 57-2017", requiredValue: "HJ 57-2017", pass: true },
      { label: "颗粒物", reportValue: "GB/T 16157-1996", requiredValue: "GB/T 16157-1996", pass: true },
      { label: "烟气流速", reportValue: "HJ/T 397-2007", requiredValue: "GB/T 16157-1996", pass: false },
    ],
    instrumentItems: [
      { name: "烟气分析仪", model: "Testo 350", calibrationDate: "2025-11-12", certValidUntil: "2026-11-11", pass: true },
      { name: "颗粒物采样器", model: "崂应 3012H", calibrationDate: "2024-12-01", certValidUntil: "2025-11-30", pass: false },
    ],
    samplingItems: [
      {
        indicator: "氮氧化物 NOx",
        sampleCount: 4,
        minRequired: 5,
        reportMean: "52.1 mg/m³",
        cemsMean: "48.4 mg/m³",
        deviation: "+7.6%",
        maxDeviation: "±15%",
        pass: false,
      },
      {
        indicator: "二氧化硫 SO₂",
        sampleCount: 6,
        minRequired: 5,
        reportMean: "14.2 mg/m³",
        cemsMean: "13.6 mg/m³",
        deviation: "+4.4%",
        maxDeviation: "±15%",
        pass: true,
      },
    ],
    attachments: [
      { id: 1, name: "2号机组废气检测报告.pdf", size: "3.5 MB", type: "pdf" },
      { id: 2, name: "采样现场照片.zip", size: "7.2 MB", type: "image" },
      { id: 3, name: "颗粒物采样器证书.pdf", size: "0.9 MB", type: "pdf" },
    ],
    reviewLogs: [
      { id: 1, actor: "系统", action: "自动核验不通过", reason: "采样组数不足、烟气流速检测方法与许可证不一致、颗粒物采样器证书已过期", time: "2026-01-12 18:03" },
    ],
  },
  {
    id: 5,
    title: "1号机组·废水",
    type: "water",
    date: "2026-01-15",
    agency: "华能检测",
    status: "pending",
    nextDate: "2026-04-15",
    dueLabel: "30天后",
    dueLevel: "normal",
    reportNo: "HN-Q1-2026-W01",
    unit: "1号机组",
    outlet: "废水排放口02",
    samplingPeriod: "2026-01-13 ~ 2026-01-14",
    formItems: [
      { label: "化学需氧量 COD", reportValue: "HJ 828-2017", requiredValue: "HJ 828-2017", pass: true },
      { label: "氨氮", reportValue: "HJ 535-2009", requiredValue: "HJ 535-2009", pass: true },
    ],
    instrumentItems: [
      { name: "紫外分光光度计", model: "T6 新世纪", calibrationDate: "2025-11-20", certValidUntil: "2026-11-19", pass: true },
    ],
    samplingItems: [
      {
        indicator: "COD",
        sampleCount: 5,
        minRequired: 4,
        reportMean: "35 mg/L",
        cemsMean: "33 mg/L",
        deviation: "+6.1%",
        maxDeviation: "±20%",
        pass: true,
      },
    ],
    attachments: [
      { id: 1, name: "1号机组废水检测报告.pdf", size: "2.4 MB", type: "pdf" },
    ],
    reviewLogs: [
      { id: 1, actor: "系统", action: "等待数据填报", time: "2026-01-15 10:20" },
    ],
  },
];

export const ROUTINE_TASKS: RoutineDetail[] = [
  // ─── 日 ─────────────────────────────────────────
  {
    id: 101,
    name: "环保设备每日点检",
    period: "daily",
    category: "设备点检",
    owner: "环保运行班",
    lastCompleted: "2026-05-15",
    nextDue: "2026-05-16",
    dueLevel: "normal",
    dueLabel: "今日",
    attachmentCount: 31,
    description: "每日对脱硫、脱硝、除尘三大系统的关键设备进行外观巡检、参数记录、异常上报。",
    basis: "《华电集团火电厂环保设施运行维护管理规定》第 4.2 条",
    frequencyText: "每日 1 次（不额外提醒）",
    attachments: [
      { id: 1, name: "2026-05 月环保设备点检记录.xlsx", size: "1.2 MB", type: "excel" },
      { id: 2, name: "脱硫系统点检表模板.pdf", size: "0.5 MB", type: "pdf" },
      { id: 3, name: "5月15日点检现场照片.zip", size: "12.4 MB", type: "image" },
    ],
    history: [
      { time: "2026-05-15 17:30", actor: "李建国", note: "脱硫塔液位、脱硝喷氨流量、电除尘电流均正常" },
      { time: "2026-05-14 17:25", actor: "王伟", note: "脱硝 2 号喷氨阀略有偏差，已记录" },
    ],
  },
  {
    id: 102,
    name: "在线监控数据每日核对",
    period: "daily",
    category: "数据核对",
    owner: "环保管理员",
    lastCompleted: "2026-05-15",
    nextDue: "2026-05-16",
    dueLevel: "normal",
    dueLabel: "今日",
    attachmentCount: 12,
    description: "核对 CEMS 数据与日报、上传至省平台的数据是否一致，发现异常立即处理。",
    basis: "《排污许可证》自行监测要求",
    frequencyText: "每日 1 次（不额外提醒）",
    attachments: [
      { id: 1, name: "2026-05 月日报数据核对表.xlsx", size: "0.9 MB", type: "excel" },
    ],
    history: [
      { time: "2026-05-15 18:00", actor: "环保管理员", note: "数据一致" },
    ],
  },
  {
    id: 103,
    name: "废水站参数记录",
    period: "daily",
    category: "运行记录",
    owner: "环保运行班",
    lastCompleted: "2026-05-15",
    nextDue: "2026-05-16",
    dueLevel: "normal",
    dueLabel: "今日",
    attachmentCount: 8,
    description: "废水处理站 pH、加药量、出水水质参数记录归档。",
    basis: "《废水处理站运行管理规程》",
    frequencyText: "每日 1 次（不额外提醒）",
    attachments: [
      { id: 1, name: "5月废水站运行记录.xlsx", size: "0.7 MB", type: "excel" },
    ],
    history: [
      { time: "2026-05-15 18:10", actor: "李建国", note: "pH 7.2，出水 COD 28 mg/L" },
    ],
  },
  // ─── 周 ─────────────────────────────────────────
  {
    id: 201,
    name: "脱硫脱硝系统周分析",
    period: "weekly",
    category: "运行分析",
    owner: "环保技术员",
    lastCompleted: "2026-05-12",
    nextDue: "2026-05-19",
    dueLevel: "very-soon",
    dueLabel: "3天后到期",
    attachmentCount: 6,
    description: "对脱硫脱硝系统本周运行情况、效率、异常事件进行汇总分析。",
    basis: "《环保设施运行月度评估办法》",
    frequencyText: "每周 1 次（提前 2 天提醒）",
    attachments: [
      { id: 1, name: "2026年第19周脱硫脱硝分析.docx", size: "1.4 MB", type: "doc" },
      { id: 2, name: "2026年第18周脱硫脱硝分析.docx", size: "1.3 MB", type: "doc" },
    ],
    history: [
      { time: "2026-05-12 11:20", actor: "张工", note: "第 19 周分析完成，脱硫效率 98.5%，脱硝效率 89.2%" },
    ],
  },
  {
    id: 202,
    name: "污染物排放周报",
    period: "weekly",
    category: "数据汇总",
    owner: "环保管理员",
    lastCompleted: "2026-05-12",
    nextDue: "2026-05-19",
    dueLevel: "very-soon",
    dueLabel: "3天后到期",
    attachmentCount: 5,
    description: "汇总本周各机组主要污染物排放量、浓度均值、超标小时数，上报给集团环保部。",
    basis: "《华电集团环保信息周报制度》",
    frequencyText: "每周 1 次（提前 2 天提醒）",
    attachments: [
      { id: 1, name: "2026-W19 排放周报.xlsx", size: "0.8 MB", type: "excel" },
    ],
    history: [
      { time: "2026-05-12 16:00", actor: "环保管理员", note: "已上报集团" },
    ],
  },
  {
    id: 203,
    name: "废气在线监测设施巡检",
    period: "weekly",
    category: "设备巡检",
    owner: "运维工程师",
    lastCompleted: "2026-05-13",
    nextDue: "2026-05-20",
    dueLevel: "normal",
    dueLabel: "4天后到期",
    attachmentCount: 4,
    description: "CEMS 在线监测仪器外观、采样系统、传输状态周度巡检。",
    basis: "《固定污染源烟气连续监测技术规范 HJ 75》",
    frequencyText: "每周 1 次（提前 2 天提醒）",
    attachments: [
      { id: 1, name: "5月CEMS周巡检记录.xlsx", size: "0.6 MB", type: "excel" },
    ],
    history: [
      { time: "2026-05-13 10:30", actor: "运维工程师", note: "采样管路温度正常，数据传输无中断" },
    ],
  },
  // ─── 月 ─────────────────────────────────────────
  {
    id: 301,
    name: "月度排放台账核对",
    period: "monthly",
    category: "台账归档",
    owner: "环保管理员",
    lastCompleted: "2026-04-30",
    nextDue: "2026-05-31",
    dueLevel: "soon",
    dueLabel: "15天后到期",
    attachmentCount: 12,
    description: "汇总月度污染物排放量、监测数据、停产时段，按排污许可证模板归档。",
    basis: "《排污许可证》台账记录要求",
    frequencyText: "每月 1 次（提前 7 天提醒）",
    attachments: [
      { id: 1, name: "2026-04 月度排放台账.xlsx", size: "2.1 MB", type: "excel" },
      { id: 2, name: "2026-03 月度排放台账.xlsx", size: "2.0 MB", type: "excel" },
    ],
    history: [
      { time: "2026-04-30 17:00", actor: "环保管理员", note: "4 月台账已归档" },
    ],
  },
  {
    id: 302,
    name: "脱硫剂质量月度抽检",
    period: "monthly",
    category: "辅材质检",
    owner: "化学专业",
    lastCompleted: "2026-04-22",
    nextDue: "2026-05-22",
    dueLevel: "very-soon",
    dueLabel: "6天后到期",
    attachmentCount: 8,
    description: "对入厂石灰石、活性炭、催化剂等辅料按月抽样化验，存档质量报告。",
    basis: "《辅料采购入厂检验制度》",
    frequencyText: "每月 1 次（提前 7 天提醒）",
    attachments: [
      { id: 1, name: "2026-04 脱硫剂检验报告.pdf", size: "0.9 MB", type: "pdf" },
    ],
    history: [
      { time: "2026-04-22 14:00", actor: "化学专业", note: "石灰石 CaO 含量 53.2%，合格" },
    ],
  },
  {
    id: 303,
    name: "环保设施月度评估",
    period: "monthly",
    category: "运行分析",
    owner: "环保技术员",
    lastCompleted: "2026-04-28",
    nextDue: "2026-05-28",
    dueLevel: "soon",
    dueLabel: "12天后到期",
    attachmentCount: 4,
    description: "对脱硫、脱硝、除尘、废水处理设施月度运行效率与异常事件进行评估。",
    basis: "《环保设施运行月度评估办法》",
    frequencyText: "每月 1 次（提前 7 天提醒）",
    attachments: [
      { id: 1, name: "2026-04 环保设施月度评估.pdf", size: "1.6 MB", type: "pdf" },
    ],
    history: [
      { time: "2026-04-28 16:30", actor: "张工", note: "4 月评估完成，整体达标" },
    ],
  },
  {
    id: 304,
    name: "无组织排放月度自检",
    period: "monthly",
    category: "排放自检",
    owner: "环保运行班",
    lastCompleted: "2026-04-25",
    nextDue: "2026-05-25",
    dueLevel: "soon",
    dueLabel: "9天后到期",
    attachmentCount: 6,
    description: "煤场、灰场、卸料区域无组织扬尘检测与抑尘措施检查。",
    basis: "《煤场环境管理办法》",
    frequencyText: "每月 1 次（提前 7 天提醒）",
    attachments: [
      { id: 1, name: "2026-04 无组织排放自检.docx", size: "0.7 MB", type: "doc" },
    ],
    history: [
      { time: "2026-04-25 15:00", actor: "环保运行班", note: "煤场抑尘正常，灰场覆盖到位" },
    ],
  },
  // ─── 季 ─────────────────────────────────────────
  {
    id: 401,
    name: "排污许可证季度执行报告",
    period: "quarterly",
    category: "合规报告",
    owner: "环保管理员",
    lastCompleted: "2026-04-10",
    nextDue: "2026-07-10",
    dueLevel: "soon",
    dueLabel: "55天后到期",
    attachmentCount: 9,
    description: "按季度向生态环境部门提交排污许可证执行报告，含监测数据、台账、合规承诺。",
    basis: "《排污许可管理条例》第 25 条",
    frequencyText: "每季 1 次（提前 15 天提醒）",
    attachments: [
      { id: 1, name: "2026-Q1 排污许可证季度执行报告.pdf", size: "4.3 MB", type: "pdf" },
      { id: 2, name: "2025-Q4 排污许可证季度执行报告.pdf", size: "4.1 MB", type: "pdf" },
    ],
    history: [
      { time: "2026-04-10 09:30", actor: "环保管理员", note: "Q1 报告已在国家平台提交" },
    ],
  },
  {
    id: 402,
    name: "环保应急演练",
    period: "quarterly",
    category: "应急管理",
    owner: "安全环保部",
    lastCompleted: "2026-03-18",
    nextDue: "2026-06-18",
    dueLevel: "soon",
    dueLabel: "33天后到期",
    attachmentCount: 7,
    description: "组织一次环保应急演练（泄漏、超标、设施故障等场景），形成演练评估报告。",
    basis: "《突发环境事件应急预案管理办法》",
    frequencyText: "每季 1 次（提前 15 天提醒）",
    attachments: [
      { id: 1, name: "2026-Q1 环保应急演练评估报告.pdf", size: "2.2 MB", type: "pdf" },
    ],
    history: [
      { time: "2026-03-18 16:00", actor: "安全环保部", note: "Q1 演练以氨水泄漏为场景，参与人数 28 人" },
    ],
  },
  {
    id: 403,
    name: "委外第三方监测计划核对",
    period: "quarterly",
    category: "监测计划",
    owner: "环保管理员",
    lastCompleted: "2026-04-05",
    nextDue: "2026-07-05",
    dueLevel: "normal",
    dueLabel: "50天后到期",
    attachmentCount: 4,
    description: "核对第三方季度监测点位、指标、频次是否覆盖排污许可证要求。",
    basis: "《排污单位自行监测技术指南》",
    frequencyText: "每季 1 次（提前 15 天提醒）",
    attachments: [
      { id: 1, name: "2026-Q2 第三方监测计划.xlsx", size: "0.5 MB", type: "excel" },
    ],
    history: [
      { time: "2026-04-05 11:00", actor: "环保管理员", note: "Q2 计划已与机构华能检测确认" },
    ],
  },
];

export const STANDARDS: VerificationStandard[] = [
  // ─── 废气 ─────────────────────────────────────────
  {
    id: 1,
    type: "gas",
    indicator: "氮氧化物 NOx",
    methods: ["HJ 692-2014", "HJ 693-2014"],
    limit: "≤ 50 mg/m³",
    sampleMin: 5,
    deviationMax: "±15%",
    source: "national",
    sourceDoc: "GB 13223-2011 火电厂大气污染物排放标准",
    active: true,
    updatedAt: "2025-09-12",
  },
  {
    id: 2,
    type: "gas",
    indicator: "二氧化硫 SO₂",
    methods: ["HJ 57-2017", "HJ 629-2011"],
    limit: "≤ 35 mg/m³",
    sampleMin: 5,
    deviationMax: "±15%",
    source: "national",
    sourceDoc: "GB 13223-2011 火电厂大气污染物排放标准",
    active: true,
    updatedAt: "2025-09-12",
  },
  {
    id: 3,
    type: "gas",
    indicator: "颗粒物",
    methods: ["GB/T 16157-1996", "HJ 836-2017"],
    limit: "≤ 10 mg/m³",
    sampleMin: 5,
    deviationMax: "±20%",
    source: "national",
    sourceDoc: "GB 13223-2011 火电厂大气污染物排放标准",
    active: true,
    updatedAt: "2025-09-12",
  },
  {
    id: 4,
    type: "gas",
    indicator: "烟气流速",
    methods: ["GB/T 16157-1996"],
    limit: "—",
    sampleMin: 5,
    deviationMax: "±10%",
    source: "national",
    sourceDoc: "GB/T 16157-1996 固定污染源排气中颗粒物测定",
    active: true,
    updatedAt: "2025-10-08",
  },
  {
    id: 5,
    type: "gas",
    indicator: "氨逃逸",
    methods: ["DL/T 260-2012"],
    limit: "≤ 2.5 mg/m³",
    sampleMin: 5,
    deviationMax: "±20%",
    source: "group",
    sourceDoc: "华电集团《脱硝设施氨逃逸内控指标》",
    active: true,
    updatedAt: "2025-11-02",
  },
  // ─── 废水 ─────────────────────────────────────────
  {
    id: 6,
    type: "water",
    indicator: "化学需氧量 COD",
    methods: ["HJ 828-2017", "HJ 924-2017"],
    limit: "≤ 50 mg/L",
    sampleMin: 4,
    deviationMax: "±20%",
    source: "national",
    sourceDoc: "GB 8978-1996 污水综合排放标准",
    active: true,
    updatedAt: "2025-08-30",
  },
  {
    id: 7,
    type: "water",
    indicator: "氨氮",
    methods: ["HJ 535-2009", "HJ 537-2009"],
    limit: "≤ 5 mg/L",
    sampleMin: 4,
    deviationMax: "±20%",
    source: "national",
    sourceDoc: "GB 8978-1996 污水综合排放标准",
    active: true,
    updatedAt: "2025-08-30",
  },
  {
    id: 8,
    type: "water",
    indicator: "总磷",
    methods: ["GB 11893-89"],
    limit: "≤ 0.5 mg/L",
    sampleMin: 4,
    deviationMax: "±25%",
    source: "national",
    sourceDoc: "GB 8978-1996 污水综合排放标准",
    active: true,
    updatedAt: "2025-08-30",
  },
  {
    id: 9,
    type: "water",
    indicator: "pH",
    methods: ["HJ 1147-2020"],
    limit: "6 ~ 9",
    sampleMin: 4,
    deviationMax: "±0.5",
    source: "expert",
    sourceDoc: "专家组《废水 pH 在线监测核验意见》",
    active: true,
    updatedAt: "2025-11-22",
  },
  // ─── 噪声 ─────────────────────────────────────────
  {
    id: 10,
    type: "noise",
    indicator: "厂界噪声（昼）",
    methods: ["GB 12348-2008"],
    limit: "≤ 60 dB(A)",
    sampleMin: 4,
    deviationMax: "—",
    source: "national",
    sourceDoc: "GB 12348-2008 工业企业厂界环境噪声排放标准",
    active: true,
    updatedAt: "2025-07-15",
  },
  {
    id: 11,
    type: "noise",
    indicator: "厂界噪声（夜）",
    methods: ["GB 12348-2008"],
    limit: "≤ 50 dB(A)",
    sampleMin: 4,
    deviationMax: "—",
    source: "national",
    sourceDoc: "GB 12348-2008 工业企业厂界环境噪声排放标准",
    active: true,
    updatedAt: "2025-07-15",
  },
  {
    id: 12,
    type: "noise",
    indicator: "采样时长",
    methods: ["GB 12348-2008"],
    limit: "≥ 10 min/点",
    sampleMin: 1,
    deviationMax: "—",
    source: "national",
    sourceDoc: "GB 12348-2008 工业企业厂界环境噪声排放标准",
    active: true,
    updatedAt: "2025-07-15",
  },
];
